name: comissio
favicon: null
layout_spectrum: 0.11535503040067852
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff7475'
    - '#75ffff'
    - '#b67374'
    - '#feb9b9'
  brandStrength: 0.15300177806057036
  lightness: 0.7894851104356349
  saturation: 0.2671019893605262
  rhythmicContrast: 0.8470883569680154
purpose: []
